### ISSUE TITLE
Form error

### ISSUE THREAD

**Issue by d00ker** [FrontendMetis/nativejs-select#8] opened 2020-04-17 02:21 UTC
If try click on custom select, the form is submitting immediately.

**Comment by FrontendMetis** [comment] 2020-04-17 21:17
Thanks for issue, the problem is resolved in new version, you can reinstall

**Closed** 2020-04-17 21:19 UTC
Labels: bug

**Comment by d00ker** [comment] 2020-04-18 08:17
@FrontendMetis thanks! Could you please to update build js?

**Comment by FrontendMetis** [comment] 2020-04-19 08:50
@d00ker  Updated in v1.0.5
